### ISSUE TITLE
Cannot use barrelstrength\sproutbase\app\import\base\FieldImporter as FieldImporter

### ISSUE THREAD

**Issue by ankitchauhan22** [barrelstrength/craft-sprout-forms#195]
In fresh Craft 3 installation, I installed Sprout Form from plugin center and got following error:

Status: Internal Server Error
Response: <pre>PHP Compile Error &#039;yii\base\ErrorException&#039; with message &#039;Cannot use barrelstrength\sproutbase\app\import\base\FieldImporter as FieldImporter because the name is already in use&#039;
in C:\wamp\www\craft3\vendor\barrelstrength\sprout-base\src\app\import\services\Importers.php:35
Stack trace:
#0 C:\wamp\www\craft3\vendor\barrelstrength\sprout-base\src\services\App.php(186): Composer\Autoload\ClassLoader-&gt;loadClass()
#1 C:\wamp\www\craft3\vendor\barrelstrength\sprout-base\src\services\App.php(186): ::spl_autoload_call()
#2 C:\wamp\www\craft3\vendor\yiisoft\yii2\base\BaseObject.php(109): barrelstrength\sproutbase\services\App-&gt;init()
#3 C:\wamp\www\craft3\vendor\barrelstrength\sprout-base\src\SproutBase.php(112): yii\base\BaseObject-&gt;__construct()
#4 C:\wamp\www\craft3\vendor\yiisoft\yii2\base\BaseObject.php(109): barrelstrength\sproutbase\SproutBase-&gt;init()
#5 C:\wamp\www\craft3\vendor\yiisoft\yii2\base\Module.php(158): yii\base\BaseObject-&gt;__construct()
#6 C:\wamp\www\craft3\vendor\barrelstrength\sprout-base\src\SproutBase.php(107): yii\base\Module-&gt;__construct()
#7 C:\wamp\www\craft3\vendor\barrelstrength\sprout-base\src\SproutBaseHelper.php(25): barrelstrength\sproutbase\SproutBase-&gt;__construct()
#8 C:\wamp\www\craft3\vendor\barrelstrength\sprout-forms\src\SproutForms.php(105): barrelstrength\sproutbase\SproutBaseHelper::registerModule()
#9 C:\wamp\www\craft3\vendor\yiisoft\yii2\base\BaseObject.php(109): barrelstrength\sproutforms\SproutForms-&gt;init()
#10 C:\wamp\www\craft3\vendor\yiisoft\yii2\base\Module.php(158): yii\base\BaseObject-&gt;__construct()
#11 C:\wamp\www\craft3\vendor\craftcms\cms\src\base\Plugin.php(113): yii\base\Module-&gt;__construct()
#12 C:\wamp\www\craft3\vendor\yiisoft\yii2\di\Container.php(383): craft\base\Plugin-&gt;__construct()
#13 C:\wamp\www\craft3\vendor\yiisoft\yii2\di\Container.php(383): ReflectionClass-&gt;newInstanceArgs()
#14 C:\wamp\www\craft3\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container-&gt;build()
#15 C:\wamp\www\craft3\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container-&gt;get()
#16 C:\wamp\www\craft3\vendor\craftcms\cms\src\services\Plugins.php(787): yii\BaseYii::createObject()
#17 C:\wamp\www\craft3\vendor\craftcms\cms\src\services\Plugins.php(199): craft\services\Plugins-&gt;createPlugin()
#18 C:\wamp\www\craft3\vendor\craftcms\cms\src\base\ApplicationTrait.php(1148): craft\services\Plugins-&gt;loadPlugins()
#19 C:\wamp\www\craft3\vendor\craftcms\cms\src\web\Application.php(109): craft\web\Application-&gt;_postInit()
#20 C:\wamp\www\craft3\vendor\yiisoft\yii2\base\BaseObject.php(109): craft\web\Application-&gt;init()
#21 C:\wamp\www\craft3\vendor\yiisoft\yii2\base\Application.php(206): yii\base\BaseObject-&gt;__construct()
#22 C:\wamp\www\craft3\vendor\craftcms\cms\src\web\Application.php(97): yii\base\Application-&gt;__construct()
#23 C:\wamp\www\craft3\vendor\yiisoft\yii2\di\Container.php(383): craft\web\Application-&gt;__construct()
#24 C:\wamp\www\craft3\vendor\yiisoft\yii2\di\Container.php(383): ReflectionClass-&gt;newInstanceArgs()
#25 C:\wamp\www\craft3\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container-&gt;build()
#26 C:\wamp\www\craft3\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container-&gt;get()
#27 C:\wamp\www\craft3\vendor\craftcms\cms\bootstrap\bootstrap.php(252): yii\BaseYii::createObject()
#28 C:\wamp\www\craft3\vendor\craftcms\cms\bootstrap\web.php(42): ::unknown()
#29 C:\wamp\www\craft3\web\index.php(20): ::unknown()
#30 {main}</pre>

### Additional info

- Craft version: 3.0.31
- PHP version: 7.0.10
- Database driver & version: MySQL 5.7.14
- Plugins & versions: 3.0.0-beta.33

**Comment by BenParizek** [comment]
Related: https://craftcms.stackexchange.com/questions/28510/error-on-updating-craft-install-with-sprout-vendor-files

**Comment by ankitchauhan22** [comment]
Changing php version to php 7.1.16 or higher will resolve the issue.

**Comment by andrelopez** [comment]
Thanks @ankitchauhan22 

I was able to recreate this issue on php 7.0.0.
