### ISSUE TITLE
Craft 2 > 3 Migration Error sproutemail_notificationemails doesn't exist

### ISSUE THREAD

**Issue by davist11** [barrelstrength/craft-sprout-forms#198]
### Description
When updating from Craft 2 > 3, we get a migration error:

```
{"error":"One of Sprout Forms’s migrations failed.","errorDetails":"Database Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viget.craft_sproutemail_notificationemails' doesn't exist
The SQL being executed was: ALTER TABLE craft_sproutemail_notificationemails ADD pluginHandle varchar(255) AFTER id
Migration: barrelstrength\\sproutforms\\migrations\\m180314_161540_craft2_to_craft3
Output:
 > add column pluginHandle string AFTER id to table {{%sproutemail_notificationemails}} ...Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viget.craft_sproutemail_notificationemails' doesn't exist
 The SQL being executed was: ALTER TABLE craft_sproutemail_notificationemails ADD pluginHandle varchar(255) AFTER id (/Users/tdavis/sites/viget/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/tdavis/sites/viget/vendor/yiisoft/yii2/db/Command.php(1263): yii\\db\\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /Users/tdavis/sites/viget/vendor/yiisoft/yii2/db/Command.php(1075): yii\\db\\Command->internalExecute('ALTER TABLE cr...')
#2 /Users/tdavis/sites/viget/vendor/yiisoft/yii2/db/Migration.php(377): yii\\db\\Command->execute()
#3 /Users/tdavis/sites/viget/vendor/barrelstrength/sprout-base/src/app/email/migrations/m180501_000003_add_notification_columns.php(22): yii\\db\\Migration->addColumn('{{%sproutemail_...', 'pluginHandle', Object(craft\\db\\mysql\\ColumnSchemaBuilder))
#4 /Users/tdavis/sites/viget/vendor/barrelstrength/sprout-forms/src/migrations/m180314_161540_craft2_to_craft3.php(85): barrelstrength\\sproutbase\\app\\email\\migrations\\m180501_000003_add_notification_columns->safeUp()
#5 /Users/tdavis/sites/viget/vendor/craftcms/cms/src/db/Migration.php(56): barrelstrength\\sproutforms\\migrations\\m180314_161540_craft2_to_craft3->safeUp()
#6 /Users/tdavis/sites/viget/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\\db\\Migration->up(true)
#7 /Users/tdavis/sites/viget/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\\db\\MigrationManager->migrateUp(Object(barrelstrength\\sproutforms\\migrations\\m180314_161540_craft2_to_craft3))
#8 /Users/tdavis/sites/viget/vendor/craftcms/cms/src/services/Updates.php(215): craft\\db\\MigrationManager->up()
#9 /Users/tdavis/sites/viget/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(443): craft\\services\\Updates->runMigrations(Array)
#10 /Users/tdavis/sites/viget/vendor/craftcms/cms/src/controllers/UpdaterController.php(207): craft\\controllers\\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\\controllers\\UpdaterController->actionMigrate()
#12 /Users/tdavis/sites/viget/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /Users/tdavis/sites/viget/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)
#14 /Users/tdavis/sites/viget/vendor/craftcms/cms/src/web/Controller.php(104): yii\\base\\Controller->runAction('migrate', Array)
#15 /Users/tdavis/sites/viget/vendor/yiisoft/yii2/base/Module.php(528): craft\\web\\Controller->runAction('migrate', Array)
#16 /Users/tdavis/sites/viget/vendor/craftcms/cms/src/web/Application.php(282): yii\\base\\Module->runAction('updater/migrate', Array)
#17 /Users/tdavis/sites/viget/vendor/craftcms/cms/src/web/Application.php(664): craft\\web\\Application->runAction('updater/migrate')
#18 /Users/tdavis/sites/viget/vendor/craftcms/cms/src/web/Application.php(236): craft\\web\\Application->_processUpdateLogic(Object(craft\\web\\Request))
#19 /Users/tdavis/sites/viget/vendor/yiisoft/yii2/base/Application.php(386): craft\\web\\Application->handleRequest(Object(craft\\web\\Request))
#20 /Users/tdavis/sites/viget/public/index.php(21): yii\\base\\Application->run()
#21 {main}
","options":[{"label":"Send for help","submit":true,"email":"sprout@barrelstrengthdesign.com","subject":"Sprout Forms update failure"}],"data":"a4c9b79f63ea6704049fbe314c0d7b552b913b2b5933e0f1c2478b212059b26e{\"migrate\":[\"environment-label\",\"inlin\",\"lever\",\"reroute\",\"sprout-fields\",\"sprout-forms\",\"super-table\",\"video-embed\",\"vz-address\"],\"returnUrl\":\"dashboard\"}"}
```

We do not have Sprout Email installed.

### Additional info

- Craft version: 3.0.29
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.23
- Plugins & versions:
  - sprout-fields: 3.1.20
  - sprout-forms 3.0.0-beta.33

**Comment by BenParizek** [comment]
@davist11 Can you confirm that you updated to the latest version of Sprout Forms on C2 before updating to Craft 3?

Sprout Forms on Craft 3 uses the Sprout Email notifications table under the hood, so the error we're troubleshooting may reference Sprout Email but is related to Sprout Forms.

**Comment by davist11** [comment]
Yup, I updated to 2.6.2 on craft 2 first

**Comment by BenParizek** [comment]
Ok, we'll try to recreate.
