### ISSUE TITLE
Exception "Calling unknown method: craft\console\Request::getSegment()" during upgrade from Craft 2

### ISSUE THREAD

**Issue by mklishevych** [barrelstrength/craft-sprout-forms#207]
### Description
Running an upgrade from craft 2 to craft 3 from the console by invoking the following command `./craft migrate/all` produces an exception:

> drop column enableTemplateOverrides from table {{%sproutforms_forms}} ... done (time: 0.187s)
Exception: Calling unknown method: craft\console\Request::getSegment() (/var/app/current/vendor/yiisoft/yii2/base/Component.php:300)
#0 /var/app/current/vendor/barrelstrength/sprout-base/src/app/email/elements/NotificationEmail.php(336): yii\base\Component->__call('getSegment', Array)
#1 /var/app/current/vendor/craftcms/cms/src/helpers/ElementHelper.php(56): barrelstrength\sproutbase\app\email\elements\NotificationEmail->getUriFormat()
#2 /var/app/current/vendor/craftcms/cms/src/validators/ElementUriValidator.php(49): craft\helpers\ElementHelper::setUniqueUri(Object(barrelstrength\sproutbase\app\email\elements\NotificationEmail))
#3 /var/app/current/vendor/yiisoft/yii2/validators/Validator.php(267): craft\validators\ElementUriValidator->validateAttribute(Object(barrelstrength\sproutbase\app\email\elements\NotificationEmail), 'uri')
#4 /var/app/current/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(barrelstrength\sproutbase\app\email\elements\NotificationEmail), Array)
#5 /var/app/current/vendor/barrelstrength/sprout-base/src/app/email/services/NotificationEmails.php(33): yii\base\Model->validate()
#6 /var/app/current/vendor/barrelstrength/sprout-forms/src/migrations/m180314_161540_craft2_to_craft3.php(148): barrelstrength\sproutbase\app\email\services\NotificationEmails->saveNotification(Object(barrelstrength\sproutbase\app\email\elements\NotificationEmail))
#7 /var/app/current/vendor/craftcms/cms/src/db/Migration.php(56): barrelstrength\sproutforms\migrations\m180314_161540_craft2_to_craft3->safeUp()
#8 /var/app/current/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#9 /var/app/current/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m180314_161540_craft2_to_craft3))
#10 /var/app/current/vendor/craftcms/cms/src/services/Updates.php(215): craft\db\MigrationManager->up()
#11 /var/app/current/vendor/craftcms/cms/src/console/controllers/MigrateController.php(243): craft\services\Updates->runMigrations(Array)
#12 [internal function]: craft\console\controllers\MigrateController->actionAll()
#13 /var/app/current/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /var/app/current/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /var/app/current/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#16 /var/app/current/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#17 /var/app/current/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#18 /var/app/current/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/all', Array)
#19 /var/app/current/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#20 /var/app/current/craft(22): yii\base\Application->run()
#21 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Sprout Forms.'

in /var/app/current/vendor/craftcms/cms/src/services/Updates.php:223

### Steps to reproduce

1. Run `./craft migrate/all`

### Additional info

- Craft version: 3.0.35
- PHP version: 7.2
- Database driver & version: MySQL
- Plugins & versions: "craftcms/cms": "3.0.35", "barrelstrength/sprout-forms": "^3.0@beta", "barrelstrength/sprout-fields": "^3.1"

**Comment by BenParizek** [comment]
Thanks for reporting @mklishevych. Sounds like we may have a bug in the logic when running migrations from the console. We'll look into it and let you know when we have a fix.

In the meantime, you can probably trigger the upgrade from the control panel and get around this issue as the getSegment method should be available during a web request.

**Comment by BenParizek** [comment]
@mklishevych This should be resolved in Sprout Forms v3.0.0-beta.37
