### ISSUE TITLE
Migration requires allowAdminChanges

### ISSUE THREAD

**Issue by chadwells** [barrelstrength/craft-sprout-forms#355]
### Description
Similar to #321 

This issue popped up again when attempting to upgrade from v3.4.3 to v3.5.1, with a migration not properly checking the plugin schema, thereby forcing an exception when trying to migrate when `allowAdminChanges=false`.

I was able to fix it by manually editing the migration file `m191005_000000_update_form_settings.php` and correcting it per [https://docs.craftcms.com/v3/extend/project-config.html#project-config-migrations](https://docs.craftcms.com/v3/extend/project-config.html#project-config-migrations). I can send a PR if needed!

For reference, the exception I was getting:

```
$ ./craft migrate/all
Yii Migration Tool (based on Yii v2.0.21)

Exception: Changes to the project config are not possible while in read-only mode. (/mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/craftcms/cms/src/services/ProjectConfig.php:355)
#0 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/barrelstrength/sprout-forms/src/migrations/m191005_000000_update_form_settings.php(53): craft\services\ProjectConfig->set('plugins.sprout-...', Array)
#1 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/craftcms/cms/src/db/Migration.php(58): barrelstrength\sproutforms\migrations\m191005_000000_update_form_settings->safeUp()
#2 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
#3 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/craftcms/cms/src/db/MigrationManager.php(159): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m191005_000000_update_form_settings))
#4 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#5 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/craftcms/cms/src/console/controllers/MigrateController.php(265): craft\services\Updates->runMigrations(Array)
#6 [internal function]: craft\console\controllers\MigrateController->actionAll()
#7 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#10 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#11 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#12 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#13 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#14 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#15 /mnt/klipschweb-data-prod1/www/klipsch3-staging/craft(22): yii\base\Application->run()
#16 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Sprout Forms.'

in /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/craftcms/cms/src/services/Updates.php:233

Stack trace:
#0 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/craftcms/cms/src/console/controllers/MigrateController.php(265): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#5 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#8 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /mnt/klipschweb-data-prod1/www/klipsch3-staging/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /mnt/klipschweb-data-prod1/www/klipsch3-staging/craft(22): yii\base\Application->run()
#11 {main}
```

**Comment by BenParizek** [comment]
Thanks @kgi-cwells 

We'll review and get this in the next release.
