### ISSUE TITLE
CSRF issues

### ISSUE THREAD

**Issue by jaydensmith** [barrelstrength/craft-sprout-forms#383]
We seem to be getting many CSRF issues recently accross multiple sites recently. It's only ever when users submit a form:

```
2019-12-09 14:05:50 [-][-][9flummgckf8ilob04fift9cvh4][error][yii\web\HttpException:400] yii\web\BadRequestHttpException: Unable to verify your data submission. in /home/forge/site.com.au/vendor/yiisoft/yii2/web/Controller.php:166
Stack trace:
#0 /home/forge/site.com.au/vendor/craftcms/cms/src/web/Controller.php(143): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /home/forge/site.com.au/vendor/yiisoft/yii2/base/Controller.php(155): craft\web\Controller->beforeAction(Object(yii\base\InlineAction))
#2 /home/forge/site.com.au/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('save-entry', Array)
#3 /home/forge/site.com.au/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#4 /home/forge/site.com.au/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('sprout-forms/en...', Array)
#5 /home/forge/site.com.au/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('sprout-forms/en...', Array)
#6 /home/forge/site.com.au/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#7 /home/forge/site.com.au/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /home/forge/site.com.au/public_html/index.php(30): yii\base\Application->run()
#9 {main}
```

**Comment by BenParizek** [comment]
@jaydensmith I'll need more info to help troubleshoot. The most common reason CSRF issues happen is when Forms are cached. The first submission will work fine and cached submissions fail as the CSRF token isn't unique to the request. This could be due to {% cache %} tags in a parent layout or a server or plugin or third party service configured to cache entire pages.

If that's not your case, I'll need more help establishing the necessary steps to recreate the issue.

**Comment by jaydensmith** [comment]
@BenParizek I'll assume for now it's a site-specific issue.
