### ISSUE TITLE
Improve asset-upload failure error-handling

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-forms#426]
Getting some occasional errors on a site that allows asset-uploads in form submission. We're getting the following errors:

```
2020-02-18 15:33:37 [-][-][hraeqohonmmsgjqvm3h2uke5m2][error][craft\services\Images::cleanImage] Tried to rotate or strip EXIF data from image and failed: insufficient image data in file `/home/forge/sitename/storage/runtime/temp/assets5e4b6921a84e38.06567537.JPG' @ error/jpeg.c/ReadJPEGImage/1039
2020-02-18 15:33:37 [-][-][hraeqohonmmsgjqvm3h2uke5m2][error][barrelstrength\sproutforms\services\Entries::saveEntry] Failed to save element: The file “assets5e4b6921a84e38.06567537.JPG” does not appear to be an image.
2020-02-18 15:33:37 [-][-][hraeqohonmmsgjqvm3h2uke5m2][error][craft\errors\ImageException] craft\errors\ImageException: The file “assets5e4b6921a84e38.06567537.JPG” does not appear to be an image. in /home/forge/sitename/vendor/craftcms/cms/src/image/Raster.php:168
Stack trace:
#0 /home/forge/sitename/vendor/craftcms/cms/src/services/Images.php(197): craft\image\Raster->loadImage('/home/forge/art...')
#1 /home/forge/sitename/vendor/craftcms/cms/src/services/Images.php(305): craft\services\Images->loadImage('/home/forge/art...')
#2 /home/forge/sitename/vendor/craftcms/cms/src/helpers/Image.php(172): craft\services\Images->cleanImage('/home/forge/art...')
#3 /home/forge/sitename/vendor/craftcms/cms/src/elements/Asset.php(1317): craft\helpers\Image::cleanImageByPath('/home/forge/art...')
#4 /home/forge/sitename/vendor/craftcms/cms/src/services/Elements.php(1973): craft\elements\Asset->afterSave(true)
#5 /home/forge/sitename/vendor/craftcms/cms/src/services/Elements.php(488): craft\services\Elements->_saveElementInternal(Object(craft\elements\Asset), true, false)
#6 /home/forge/sitename/vendor/barrelstrength/sprout-forms/src/fields/formfields/FileUpload.php(460): craft\services\Elements->saveElement(Object(craft\elements\Asset))
#7 /home/forge/sitename/vendor/craftcms/cms/src/base/Element.php(2124): barrelstrength\sproutforms\fields\formfields\FileUpload->afterElementSave(Object(barrelstrength\sproutforms\elements\Entry), true)
#8 /home/forge/sitename/vendor/barrelstrength/sprout-forms/src/elements/Entry.php(381): craft\base\Element->afterSave(true)
#9 /home/forge/sitename/vendor/craftcms/cms/src/services/Elements.php(1973): barrelstrength\sproutforms\elements\Entry->afterSave(true)
#10 /home/forge/sitename/vendor/craftcms/cms/src/services/Elements.php(488): craft\services\Elements->_saveElementInternal(Object(barrelstrength\sproutforms\elements\Entry), true, false)
#11 /home/forge/sitename/vendor/barrelstrength/sprout-forms/src/services/Entries.php(310): craft\services\Elements->saveElement(Object(barrelstrength\sproutforms\elements\Entry))
#12 /home/forge/sitename/vendor/barrelstrength/sprout-forms/src/controllers/EntriesController.php(146): barrelstrength\sproutforms\services\Entries->saveEntry(Object(barrelstrength\sproutforms\elements\Entry))
#13 /home/forge/sitename/vendor/barrelstrength/sprout-forms/src/controllers/EntriesController.php(126): barrelstrength\sproutforms\controllers\EntriesController->saveEntryInCraft(Object(barrelstrength\sproutforms\elements\Entry))
#14 [internal function]: barrelstrength\sproutforms\controllers\EntriesController->actionSaveEntry()
#15 /home/forge/sitename/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /home/forge/sitename/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /home/forge/sitename/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('save-entry', Array)
#18 /home/forge/sitename/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#19 /home/forge/sitename/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('sprout-forms/en...', Array)
#20 /home/forge/sitename/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('sprout-forms/en...', Array)
#21 /home/forge/sitename/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /home/forge/sitename/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /home/forge/sitename/public_html/index.php(30): yii\base\Application->run()
#24 {main}

```

And If I check these temporary images out, they're 0 bytes. Not sure what's going on here (user error, or server), but at the very least, it should provide better feedback if something does go wrong. Right now, the user is hit with a 500 Internal Server Error, with no real description of the issue. It'd be good to wrap this in a try/catch (if possible) and just report back there was an error uploading an asset.

Our form contains multiple asset fields, but not all of them fail.

**Comment by BenParizek** [comment]
Thanks @engram-design.

I'll look into this when I have a chance and see if I can recreate it or get better logging in there for you.

**Comment by BenParizek** [comment]
@engram-design We've made several updates in the most recent release (v3.8.8) to clean up the File Upload field type implementation and align it more with Craft's Asset field without duplicating as much code. Our first implementation had a lot of duplicated code from Craft and I think it lead to a few inconsistencies in how assets got processed as Craft's underlying codebase changed. 

I'm going to close this out for now and let's see if these updates improve things. If you still see these errors, please re-open and let me know where you'd like to see that try/catch. I can consider adding it or trying to get Craft in core as this would probably be good feedback to have in any upload scenario as the File Upload field is just piggybacking on the Assets field and using the same underlying logic for processing images.
