### ISSUE TITLE
Craft 2 to 3 migration failures

### ISSUE THREAD

**Issue by OscarBarrett** [barrelstrength/craft-sprout-forms#454]
### Description (screenshots, logs, ...)

We ran into a failure that seems to have been introduced in this commit a week ago: https://github.com/barrelstrength/craft-sprout-forms/commit/f057be47593e52c46951d74f188ba3e1bec9cc07

We don't have Sprout Email installed on the site we attempted the update for.

```bash
Database Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.craft_sproutemail_campaignemails' doesn't exist
The SQL being executed was: ALTER TABLE craft_sproutemail_campaignemails ADD listSettings varchar(255) AFTER recipients

Migration: barrelstrength\\sproutforms\\migrations\\m180314_161540_craft2_to_craft3

Output:

 > add column listSettings string AFTER recipients to table {{%sproutemail_campaignemails}} ...Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.craft_sproutemail_campaignemails' doesn't exist
The SQL being executed was: ALTER TABLE craft_sproutemail_campaignemails ADD listSettings varchar(255) AFTER recipients (/app/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /app/vendor/yiisoft/yii2/db/Command.php(1295): yii\\db\\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1091): yii\\db\\Command->internalExecute('ALTER TABLE cr...')
#2 /app/vendor/yiisoft/yii2/db/Migration.php(377): yii\\db\\Command->execute()
#3 /app/vendor/barrelstrength/sprout-base-email/src/migrations/m181128_000000_add_list_settings_column.php(28): yii\\db\\Migration->addColumn('{{%sproutemail_...', 'listSettings', Object(craft\\db\\mysql\\ColumnSchemaBuilder))
#4 /app/vendor/barrelstrength/sprout-forms/src/migrations/m180314_161540_craft2_to_craft3.php(142): barrelstrength\\sproutbaseemail\\migrations\\m181128_000000_add_list_settings_column->safeUp()
#5 /app/vendor/craftcms/cms/src/db/Migration.php(52): barrelstrength\\sproutforms\\migrations\\m180314_161540_craft2_to_craft3->safeUp()
#6 /app/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\\db\\Migration->up(true)
#7 /app/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\\db\\MigrationManager->migrateUp(Object(barrelstrength\\sproutforms\\migrations\\m180314_161540_craft2_to_craft3))
#8 /app/vendor/craftcms/cms/src/services/Updates.php(233): craft\\db\\MigrationManager->up()
#9 /app/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\\services\\Updates->runMigrations(Array)
#10 /app/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\\controllers\\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\\controllers\\UpdaterController->actionMigrate()
#12 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)
#14 /app/vendor/craftcms/cms/src/web/Controller.php(178): yii\\base\\Controller->runAction('migrate', Array)
#15 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\\web\\Controller->runAction('migrate', Array)
#16 /app/vendor/craftcms/cms/src/web/Application.php(291): yii\\base\\Module->runAction('updater/migrate', Array)
#17 /app/vendor/craftcms/cms/src/web/Application.php(646): craft\\web\\Application->runAction('updater/migrate')
#18 /app/vendor/craftcms/cms/src/web/Application.php(243): craft\\web\\Application->_processUpdateLogic(Object(craft\\web\\Request))
#19 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\\web\\Application->handleRequest(Object(craft\\web\\Request))
#20 /app/web/index.php(21): yii\\base\\Application->run()
#21 
```

If we try 3.8.7, we get the following failure. Trying again lets us complete the upgrade, though I don't know if this leaves us in a bad state.

```
Unknown Property: Setting unknown property: barrelstrength\sproutbasereports\records\Report::sortOrder

Migration: barrelstrength\sproutforms\migrations\m190318_000001_update_record_to_element_types_sproutforms

Output:

Exception: Setting unknown property: barrelstrength\sproutbasereports\records\Report::sortOrder (/app/vendor/yiisoft/yii2/base/Component.php:209)
#0 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\base\Component->__set('sortOrder', NULL)
#1 /app/vendor/craftcms/cms/src/db/ActiveRecord.php(41): yii\db\BaseActiveRecord->__set('sortOrder', NULL)
#2 /app/vendor/barrelstrength/sprout-base-reports/src/elements/Report.php(497): craft\db\ActiveRecord->__set('sortOrder', NULL)
#3 /app/vendor/craftcms/cms/src/services/Elements.php(2124): barrelstrength\sproutbasereports\elements\Report->afterSave(true)
#4 /app/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal(Object(barrelstrength\sproutbasereports\elements\Report), false, false, true)
#5 /app/vendor/barrelstrength/sprout-base-reports/src/migrations/m190305_000002_update_record_to_element_types.php(60): craft\services\Elements->saveElement(Object(barrelstrength\sproutbasereports\elements\Report), false)
#6 /app/vendor/barrelstrength/sprout-forms/src/migrations/m190318_000001_update_record_to_element_types_sproutforms.php(29): barrelstrength\sproutbasereports\migrations\m190305_000002_update_record_to_element_types->safeUp()
#7 /app/vendor/craftcms/cms/src/db/Migration.php(52): barrelstrength\sproutforms\migrations\m190318_000001_update_record_to_element_types_sproutforms->safeUp()
#8 /app/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#9 /app/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m190318_000001_update_record_to_element_types_sproutforms))
#10 /app/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#11 /app/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#12 /app/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#13 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#14 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /app/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#17 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#18 /app/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#19 /app/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#20 /app/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#21 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /app/web/index.php(21): yii\base\Application->run()
#23 {main}
```

### Additional info

- Craft version: 2.7.2 -> 3.4.10.1
- PHP version: 7.3
- Database driver & version: MySQL 5.7
- Plugins & versions: Sprout Forms 2.6.4, Sprout Reports 0.10.1, Sprout Fields 2.2.0 - updating to latest for all

**Comment by BenParizek** [comment]
Thanks, @OscarBarrett. I'm catching up on support this week after a couple of busy weeks. I'll update this thread once we have a fix.

**Comment by BenParizek** [comment]
I believe these items have been addressed in the latest release v3.10.0.

If you're still running into any issues, please re-open or hit me up on Craft Discord and we can take a look at your database on a screen share and figure out what's going on.

**Comment by espensgr** [comment]
I'm getting this error too.
I dont have the campaign mails plugin, but the other plugins and are getting the second error:

```
Yii Migration Tool (based on Yii v2.0.38)

Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Sprout Forms.'

in /app/vendor/craftcms/cms/src/services/Updates.php:265

Caused by: Exception 'craft\errors\MigrationException' with message 'An error occurred while executing the "barrelstrength\sproutforms\migrations\m190318_000001_update_record_to_element_types_sproutforms migration: Setting unknown property: barrelstrength\sproutbasereports\records\Report::sortOrder'

in /app/vendor/craftcms/cms/src/db/MigrationManager.php:252

Caused by: Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: barrelstrength\sproutbasereports\records\Report::sortOrder'

in /app/vendor/yiisoft/yii2/base/Component.php:209

Stack trace:
#0 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\base\Component->__set('sortOrder', NULL)
#1 /app/vendor/craftcms/cms/src/db/ActiveRecord.php(54): yii\db\BaseActiveRecord->__set('sortOrder', NULL)
#2 /app/vendor/barrelstrength/sprout-base-reports/src/elements/Report.php(500): craft\db\ActiveRecord->__set('sortOrder', NULL)
#3 /app/vendor/craftcms/cms/src/services/Elements.php(2454): barrelstrength\sproutbasereports\elements\Report->afterSave(true)
#4 /app/vendor/craftcms/cms/src/services/Elements.php(755): craft\services\Elements->_saveElementInternal(Object(barrelstrength\sproutbasereports\elements\Report), false, false, true)
#5 /app/vendor/barrelstrength/sprout-base-reports/src/migrations/m190305_000002_update_record_to_element_types.php(60): craft\services\Elements->saveElement(Object(barrelstrength\sproutbasereports\elements\Report), false)
#6 /app/vendor/barrelstrength/sprout-forms/src/migrations/m190318_000001_update_record_to_element_types_sproutforms.php(27): barrelstrength\sproutbasereports\migrations\m190305_000002_update_record_to_element_types->safeUp()
#7 /app/vendor/craftcms/cms/src/db/Migration.php(52): barrelstrength\sproutforms\migrations\m190318_000001_update_record_to_element_types_sproutforms->safeUp()
#8 /app/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#9 /app/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m190318_000001_update_record_to_element_types_sproutforms))
#10 /app/vendor/craftcms/cms/src/services/Updates.php(257): craft\db\MigrationManager->up()
#11 /app/vendor/craftcms/cms/src/console/controllers/MigrateController.php(329): craft\services\Updates->runMigrations(Array)
#12 [internal function]: craft\console\controllers\MigrateController->actionAll()
#13 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /app/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#15 /app/vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction('all', Array)
#16 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#17 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#18 /app/vendor/craftcms/cms/src/console/Application.php(88): yii\console\Application->runAction('migrate/all', Array)
#19 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#20 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#21 /app/craft(23): yii\base\Application->run()
#22 {main}

```
And i have to run the ./craft migrate/all twice to get the sprout migrations to run.
If you found a manual fix for this that would be nice to 

### Additional info

- Craft version: 2.7.10 -> 3.5.10
- PHP version: 7.2
- Database driver & version: MySQL 5.7
- Plugins & versions: Sprout Forms 2.6.4, Sprout Reports 0.10.1, Sprout Fields 2.2.0 - updating to latest for all

**Comment by BenParizek** [comment]
@espensgr I'm currently working on a release that should address these migration issues more comprehensively. I can't promise a date yet, but it's my primary focus right now. I've re-opened this and will update this thread once we get a release out that addresses it.

**Comment by espensgr** [comment]
Any chance the release is coming within this year?
It's just to inform our costumer if we are able to migrate their site this year 😄

**Comment by espensgr** [comment]
Any update on the release or this bug?

**Comment by BenParizek** [comment]
This should be resolved in the latest release.

Just to note, I'm catching up on several support tickets and working on a large update to improve the migration process that has been causing a lot of migration issues in our plugins. There will likely be several smaller updates coming out over the next couple of weeks so, if waiting on the migration is an option, It may be worth holding off on updating until we get Sprout Reports v2.0 out the door which should get things into a lot better shape and address a number of smaller issues all at once.

Related: https://github.com/barrelstrength/craft-sprout-reports/issues/95

**Comment by espensgr** [comment]
The migrations are working now, thanks
