### ISSUE TITLE
Database Exception: SQLSTATE[22007]: Invalid datetime format

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#509]
### Description (screenshots, logs, ...)
Trying to update from 3.11.7 to 3.12.2, the migration fails, with the attached log.
### Additional info

- Craft version: 3.4.27
- PHP version: 7.4.6
- Database driver & version:  MySQL
- Plugins & versions:

Admin Bar   3.1.10
Amazon S3   1.2.8
Control Panel Nav   3.0.12
Cookies   1.1.12
Dashboard Begone   1.0.1
Element API   2.6.0
Field Manager   2.1.6
Imager   v2.4.0
Linkit   1.1.11
Mix   1.5.2
Redactor   2.6.1
Retour   3.1.40
SEOmatic   3.3.10
Sprout Forms   3.11.7
Super Table   2.5.1

```
Database Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: 'sproutreports.users'
The SQL being executed was: ALTER TABLE craft_sproutreports_reports CHANGE dataSourceId dataSourceId int(11)

Migration: barrelstrength\sproutforms\migrations\m200520_000002_update_datasourceId_column_type_sproutforms

Output:

> alter column dataSourceId in table {{%sproutreports_reports}} to integer ...Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: 'sproutreports.users'
The SQL being executed was: ALTER TABLE craft_sproutreports_reports CHANGE dataSourceId dataSourceId int(11) (/Users/user_name/Sites/site_name/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /Users/user_name/Sites/site_name/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /Users/user_name/Sites/site_name/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('ALTER TABLE cr...')
#2 /Users/user_name/Sites/site_name/vendor/yiisoft/yii2/db/Migration.php(420): yii\db\Command->execute()
#3 /Users/user_name/Sites/site_name/vendor/barrelstrength/sprout-base-reports/src/migrations/m200520_000002_update_datasourceId_column_type.php(25): yii\db\Migration->alterColumn('{{%sproutreport...', 'dataSourceId', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /Users/user_name/Sites/site_name/vendor/barrelstrength/sprout-forms/src/migrations/m200520_000002_update_datasourceId_column_type_sproutforms.php(18): barrelstrength\sproutbasereports\migrations\m200520_000002_update_datasourceId_column_type->safeUp()
#5 /Users/user_name/Sites/site_name/vendor/craftcms/cms/src/db/Migration.php(52): barrelstrength\sproutforms\migrations\m200520_000002_update_datasourceId_column_type_sproutforms->safeUp()
#6 /Users/user_name/Sites/site_name/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#7 /Users/user_name/Sites/site_name/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m200520_000002_update_datasourceId_column_type_sproutforms))
#8 /Users/user_name/Sites/site_name/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#9 /Users/user_name/Sites/site_name/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#10 /Users/user_name/Sites/site_name/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /Users/user_name/Sites/site_name/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /Users/user_name/Sites/site_name/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /Users/user_name/Sites/site_name/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#15 /Users/user_name/Sites/site_name/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 /Users/user_name/Sites/site_name/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#17 /Users/user_name/Sites/site_name/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#18 /Users/user_name/Sites/site_name/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 /Users/user_name/Sites/site_name/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /Users/user_name/Sites/site_name/public/index.php(21): yii\base\Application->run()
#21 /Users/user_name/.composer/vendor/laravel/valet/server.php(158): require('/Users/darylkni...')
#22 {main}
```

_my own reference: GDB_

**Comment by BenParizek** [comment]
Closing this out to consolidate with ticket: https://github.com/barrelstrength/craft-sprout-forms/issues/492
