### ISSUE TITLE
Error saving Email Dropdown

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#525]
### Description (screenshots, logs, ...)

Just updated a client site to Sprout Forms 3.12.2 and am now unable to save an email dropdown field:

```
2020-08-13 11:16:36 [-][1][-][error][barrelstrength\sproutforms\controllers\FieldsController::actionSaveField] Field does not validate.
2020-08-13 11:16:36 [-][1][-][error][Twig\Error\RuntimeError] yii\base\ErrorException: Array to string conversion in /var/sites/m/sitenameremoved[mnc].co.uk/storage/runtime/compiled_templates/50/504d6126cb07e47aa6578c246032caba066da7c67c862042f314988bc5525a16.php:123
Stack trace:
#0 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(8, 'Array to string...', '/var/sites/m/ma...', 123)
#1 /var/sites/m/sitenameremoved[mnc].co.uk/storage/runtime/compiled_templates/50/504d6126cb07e47aa6578c246032caba066da7c67c862042f314988bc5525a16.php(123): craft\web\ErrorHandler->handleError(8, 'Array to string...', '/var/sites/m/ma...', 123, Array)
#2 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/Template.php(407): __TwigTemplate_09de3a4da6ccc9fb79a3b04fcc761b1d473268a55ecd2889c5377282ca01bae8->doDisplay(Array, Array)
#3 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /var/sites/m/sitenameremoved[mnc].co.uk/storage/runtime/compiled_templates/26/26706564066cb8b1f5ac83f15c6967f641fcce2fdec1808b7a9fe3bff5482408.php(441): Twig\Template->display(Array)
#5 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/Extension/CoreExtension.php(1109): __TwigTemplate_f6a12f21ba6cc378737802e7de9fcb251a02d248e25b5307d035cf807d9a22d8->macro_select(Array)
#6 /var/sites/m/sitenameremoved[mnc].co.uk/storage/runtime/compiled_templates/ef/ef99ecac5485c82e768e0f17f942ddde2dd85409746fd0027b4d4ceb786a44fa.php(58): twig_call_macro(Object(__TwigTemplate_f6a12f21ba6cc378737802e7de9fcb251a02d248e25b5307d035cf807d9a22d8), 'macro_select', Array, 11, Array, Object(Twig\Source))
#7 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/Template.php(407): __TwigTemplate_f50a987ed2d23f3dabb895c6981c4e67a24fc97838a56d0efbbb828fb3670945->doDisplay(Array, Array)
#8 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#10 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#11 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#12 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/craftcms/cms/src/web/View.php(375): Twig\Environment->render('sprout-forms/_c...', Array)
#13 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/barrelstrength/sprout-forms/src/fields/formfields/EmailDropdown.php(205): craft\web\View->renderTemplate('sprout-forms/_c...', Array)
#14 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/barrelstrength/sprout-forms/src/controllers/FieldsController.php(397): barrelstrength\sproutforms\fields\formfields\EmailDropdown->getExampleInputHtml()
#15 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/barrelstrength/sprout-forms/src/controllers/FieldsController.php(185): barrelstrength\sproutforms\controllers\FieldsController->returnJson(false, Object(barrelstrength\sproutforms\fields\formfields\EmailDropdown), Object(barrelstrength\sproutforms\elements\Form), NULL, '87')
#16 [internal function]: barrelstrength\sproutforms\controllers\FieldsController->actionSaveField()
#17 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#19 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('save-field', Array)
#20 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-field', Array)
#21 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('sprout-forms/fi...', Array)
#22 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('sprout-forms/fi...', Array)
#23 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#24 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#25 /var/sites/m/sitenameremoved[mnc].co.uk/public_html/index.php(21): yii\base\Application->run()
#26 {main}

Next Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Array to string conversion"). in /var/sites/m/sitenameremoved[mnc].co.uk/vendor/craftcms/cms/src/templates/_includes/forms/select.html:31
Stack trace:
#0 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#1 /var/sites/m/sitenameremoved[mnc].co.uk/storage/runtime/compiled_templates/26/26706564066cb8b1f5ac83f15c6967f641fcce2fdec1808b7a9fe3bff5482408.php(441): Twig\Template->display(Array)
#2 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/Extension/CoreExtension.php(1109): __TwigTemplate_f6a12f21ba6cc378737802e7de9fcb251a02d248e25b5307d035cf807d9a22d8->macro_select(Array)
#3 /var/sites/m/sitenameremoved[mnc].co.uk/storage/runtime/compiled_templates/ef/ef99ecac5485c82e768e0f17f942ddde2dd85409746fd0027b4d4ceb786a44fa.php(58): twig_call_macro(Object(__TwigTemplate_f6a12f21ba6cc378737802e7de9fcb251a02d248e25b5307d035cf807d9a22d8), 'macro_select', Array, 11, Array, Object(Twig\Source))
#4 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/Template.php(407): __TwigTemplate_f50a987ed2d23f3dabb895c6981c4e67a24fc97838a56d0efbbb828fb3670945->doDisplay(Array, Array)
#5 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#7 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#8 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#9 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/craftcms/cms/src/web/View.php(375): Twig\Environment->render('sprout-forms/_c...', Array)
#10 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/barrelstrength/sprout-forms/src/fields/formfields/EmailDropdown.php(205): craft\web\View->renderTemplate('sprout-forms/_c...', Array)
#11 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/barrelstrength/sprout-forms/src/controllers/FieldsController.php(397): barrelstrength\sproutforms\fields\formfields\EmailDropdown->getExampleInputHtml()
#12 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/barrelstrength/sprout-forms/src/controllers/FieldsController.php(185): barrelstrength\sproutforms\controllers\FieldsController->returnJson(false, Object(barrelstrength\sproutforms\fields\formfields\EmailDropdown), Object(barrelstrength\sproutforms\elements\Form), NULL, '87')
#13 [internal function]: barrelstrength\sproutforms\controllers\FieldsController->actionSaveField()
#14 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('save-field', Array)
#17 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-field', Array)
#18 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('sprout-forms/fi...', Array)
#19 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('sprout-forms/fi...', Array)
#20 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#21 /var/sites/m/sitenameremoved[mnc].co.uk/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /var/sites/m/sitenameremoved[mnc].co.uk/public_html/index.php(21): yii\base\Application->run()
#23 {main}
2020-08-13 11:16:36 [-][1][-][info][application] $_GET = [
    'p' => 'admin/actions/sprout-forms/fields/save-field'
]

$_POST = [
    'formId' => '864'
    'fieldId' => '50'
    'required' => '1'
    'name' => 'Department'
    'instructions' => 'NEW Enquiry - Please select New Membership Enquiries and complete all sections of the form below .........................
EXISTING Members - Please select the Coach/Committee Member you would you like to contact and add your personal details and message? No need to complete the rest of the form.'
    'types' => [
        'barrelstrength\\sproutforms\\fields\\formfields\\SingleLine' => [
            'placeholder' => ''
            'charLimit' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Paragraph' => [
            'placeholder' => ''
            'initialRows' => '4'
            'charLimit' => ''
            'columnType' => 'text'
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\MultipleChoice' => [
            'options' => [
                0 => [
                    'label' => ''
                    'value' => ''
                    'default' => ''
                ]
            ]
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Dropdown' => [
            'options' => [
                0 => [
                    'isOptgroup' => ''
                    'label' => ''
                    'value' => ''
                    'default' => ''
                ]
            ]
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Checkboxes' => [
            'options' => [
                0 => [
                    'label' => ''
                    'value' => ''
                    'default' => ''
                ]
            ]
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Number' => [
            'min' => ''
            'max' => ''
            'decimals' => '0'
            'size' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\FileUpload' => [
            'sources' => '*'
            'defaultUploadLocationSource' => 'folder:d8d1f272-faa2-489c-a372-bd7f16ceca7e'
            'defaultUploadLocationSubpath' => ''
            'singleUploadLocationSource' => 'folder:d8d1f272-faa2-489c-a372-bd7f16ceca7e'
            'singleUploadLocationSubpath' => ''
            'restrictFiles' => ''
            'limit' => ''
            'selectionLabel' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\SectionHeading' => [
            'notes' => ''
            'output' => 'richText'
            'hideLabel' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Name' => [
            'displayMultipleFields' => ''
            'displayPrefix' => ''
            'displayMiddleName' => ''
            'displaySuffix' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\OptIn' => [
            'optInMessage' => 'Agree to terms?'
            'selectedByDefault' => ''
            'optInValueWhenTrue' => 'Yes'
            'optInValueWhenFalse' => 'No'
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Email' => [
            'placeholder' => ''
            'customPatternToggle' => ''
            'customPattern' => ''
            'customPatternErrorMessage' => ''
            'uniqueEmail' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\EmailDropdown' => [
            'options' => [
                0 => [
                    'label' => 'New Membership Enquiries'
                    'value' => 'louise.gelhardt@akzonobel.com'
                    'default' => '1'
                ]
                1 => [
                    'label' => 'Yr 2/3 New Members Coach'
                    'value' => 'jueymacgregor@aol.com'
                    'default' => ''
                ]
                2 => [
                    'label' => 'Yr 4 REC Coach'
                    'value' => 'jueymacgregor@aol.com'
                    'default' => ''
                ]
                3 => [
                    'label' => 'Yr 5 REC Coach'
                    'value' => 'jueymacgregor@aol.com'
                    'default' => ''
                ]
                4 => [
                    'label' => 'Yr 6 REC Coach'
                    'value' => 'bev.goodman@sky.com'
                    'default' => ''
                ]
                5 => [
                    'label' => 'Yr 7 REC Coach'
                    'value' => 'jueymacgregor@aol.com'
                    'default' => ''
                ]
                6 => [
                    'label' => 'Yr 8 REC Coach'
                    'value' => 'jueymacgregor@aol.com'
                    'default' => ''
                ]
                7 => [
                    'label' => 'Yr 9 REC Coach'
                    'value' => 'jueymacgregor@aol.com'
                    'default' => ''
                ]
                8 => [
                    'label' => 'Yr 3 Coach'
                    'value' => 'sallygray.home@gmail.com'
                    'default' => ''
                ]
                9 => [
                    'label' => 'Yr 4 DEV Coach'
                    'value' => 'bev.goodman@sky.com'
                    'default' => ''
                ]
                10 => [
                    'label' => 'Yr 5 DEV Coach'
                    'value' => 'geordiedoc@yahoo.co.uk'
                    'default' => ''
                ]
                11 => [
                    'label' => 'Yr 6 COMP Coach'
                    'value' => 'sallygray.home@gmail.com'
                    'default' => ''
                ]
                12 => [
                    'label' => 'Yr 7 COMP Coach'
                    'value' => 'patrickandrachael@talktalk.net'
                    'default' => ''
                ]
                13 => [
                    'label' => 'Yr 8 COMP Coach '
                    'value' => 'patrickandrachael@talktalk.net'
                    'default' => ''
                ]
                14 => [
                    'label' => 'Yr 9 COMP Coach'
                    'value' => 'marina.bowles700@btinternet.com'
                    'default' => ''
                ]
                15 => [
                    'label' => 'Yr 10/11 COMP Coach'
                    'value' => 'nettinoo@hotmail.com'
                    'default' => ''
                ]
                16 => [
                    'label' => 'Club Secretary '
                    'value' => 'nettinoo@hotmail.com'
                    'default' => ''
                ]
                17 => [
                    'label' => 'Club Chairperson'
                    'value' => 'sallygray.home@gmail.com'
                    'default' => ''
                ]
                18 => [
                    'label' => 'Safeguarding Officer'
                    'value' => 'palmer_lesley@btconnect.com'
                    'default' => ''
                ]
                19 => [
                    'label' => 'Treasurer'
                    'value' => 'anne_hopkins@sky.com'
                    'default' => ''
                ]
                20 => [
                    'label' => 'test'
                    'value' => 'daryl@codeknight.co.uk'
                    'default' => ''
                ]
            ]
            'cssClasses' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Url' => [
            'placeholder' => ''
            'customPatternToggle' => ''
            'customPattern' => ''
            'customPatternErrorMessage' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Phone' => [
            'country' => 'AF'
            'limitToSingleCountry' => ''
            'placeholder' => ''
            'customPatternErrorMessage' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Address' => [
            'defaultLanguage' => 'en'
            'defaultCountry' => 'US'
            'showCountryDropdown' => '1'
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Date' => [
            'dateTime' => 'showDate'
            'minimumDate' => ''
            'maximumDate' => ''
            'minuteIncrement' => '30'
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\CustomHtml' => [
            'customHtml' => ''
            'hideLabel' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\MultiSelect' => [
            'options' => [
                0 => [
                    'isOptgroup' => ''
                    'label' => ''
                    'value' => ''
                    'default' => ''
                ]
            ]
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\RegularExpression' => [
            'placeholder' => ''
            'customPattern' => ''
            'customPatternErrorMessage' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Hidden' => [
            'value' => ''
            'allowEdits' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Invisible' => [
            'value' => ''
            'allowEdits' => ''
            'hideValue' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Categories' => [
            'source' => 'group:4f134bbd-e861-4159-aa9d-e44349af95f0'
            'selectionLabel' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Entries' => [
            'sources' => '*'
            'limit' => ''
            'selectionLabel' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Tags' => [
            'source' => 'taggroup:4051ac85-7bf5-4cf4-b219-8c8c055c117d'
            'selectionLabel' => ''
        ]
        'barrelstrength\\sproutforms\\fields\\formfields\\Users' => [
            'sources' => '*'
            'limit' => ''
            'selectionLabel' => ''
            'usernameFormat' => 'fullName'
        ]
    ]
    'tabId' => '87'
    'handle' => 'department'
    'type' => 'barrelstrength\\sproutforms\\fields\\formfields\\EmailDropdown'
]

$_FILES = []

$_COOKIE = [
    'CRAFT_CSRF_TOKEN' => '•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    '1031b8c41dfff97a311a7ac99863bdc5_username' => 'e376cfd969153b9658859d8c12580a8a82f8d461b0b969b9bf5fcaefdbb74230a:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_username\";i:1;s:22:\"daryl@codeknight.co.uk\";}'
    '_ga' => 'GA1.3.1859388290.1597310591'
    '_gid' => 'GA1.3.1221850907.1597310591'
    '__cfduid' => 'd5dd37eb90a13cee524c85c767405fc8d1597312551'
    '1031b8c41dfff97a311a7ac99863bdc5_identity' => '8072afe04ea218bfb79d726aeac8e36180bad20cec0012f9cebd591515258333a:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_identity\";i:1;s:250:\"[\"1\",\"[\\\"yVQI1wScjIFqbDuwRj_ATB-edFpJgX9vh6uPKwGmU-1my1-DbOPrTMZxsajaaOuw4njRBGkcqgfmp4M12GOkIxY6p2Gj8FHAp2Az\\\",null,\\\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36\\\"]\",3600]\";}'
    'CraftSessionId' => '501fc4a35b34aff131774e2d24d7a738'
]

$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => []
    'bd62416aa8538ede709019a5e113eea5__auth_access' => [
        0 => 'editStructure:1'
    ]
    'dupe5f350a3b2904f2.92358343' => true
    'sprout-forms-javascript-captcha' => 'alojsaa09905be77bcca9a54a1720a39bf1c8'
    '1031b8c41dfff97a311a7ac99863bdc5__token' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    '1031b8c41dfff97a311a7ac99863bdc5__id' => '1'
    '1031b8c41dfff97a311a7ac99863bdc5__expire' => 1597317396
    'dc5f35127f8c178' => true
    'sprout-forms-jckf9557abe073911e1bbba15d91d5f99ba' => 'sprout-forms-jcvc40495784b1931ea026f43a382ffac92'
    'sprout-forms-jcvc40495784b1931ea026f43a382ffac92' => true
]

$_SERVER = [
    'CONTENT_LENGTH' => '17449'
    'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8'
    'DOCUMENT_ROOT' => '/var/sites/m/sitenameremoved[mnc].co.uk/public_html'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'HTTPS' => 'On'
    'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
    'HTTP_ACCEPT_LANGUAGE' => 'en-GB,en;q=0.9,fi;q=0.8,de;q=0.7,nl;q=0.6'
    'HTTP_CACHE_CONTROL' => 'max-age=0'
    'HTTP_CONNECTION' => 'close'
    'HTTP_COOKIE' => 'CRAFT_CSRF_TOKEN=443e9dee03cef74a43483f6d5a721fbcb70472747eba36ae9fe8c8a68df6a8dfa%3A2%3A%7Bi%3A0%3Bs%3A16%3A%22CRAFT_CSRF_TOKEN%22%3Bi%3A1%3Bs%3A208%3A%22BOk9m3CavxF0RwbFXOpv2Wu49T52p6J3oilLpH4Y%7C02fcb2420b28d3b6d1cae98286e972a94b9eec106a0745fb2ef4aa9e3172b3e3BOk9m3CavxF0RwbFXOpv2Wu49T52p6J3oilLpH4Y%7C1%7C%242y%2413%245GGV.NOI0wkA.XbyffG6D.v%2FvFRMhAVJ6oqxtc42ci5W9VD6hu0eq%22%3B%7D; 1031b8c41dfff97a311a7ac99863bdc5_username=e376cfd969153b9658859d8c12580a8a82f8d461b0b969b9bf5fcaefdbb74230a%3A2%3A%7Bi%3A0%3Bs%3A41%3A%221031b8c41dfff97a311a7ac99863bdc5_username%22%3Bi%3A1%3Bs%3A22%3A%22daryl%40codeknight.co.uk%22%3B%7D; _ga=GA1.3.1859388290.1597310591; _gid=GA1.3.1221850907.1597310591; __cfduid=d5dd37eb90a13cee524c85c767405fc8d1597312551; 1031b8c41dfff97a311a7ac99863bdc5_identity=8072afe04ea218bfb79d726aeac8e36180bad20cec0012f9cebd591515258333a%3A2%3A%7Bi%3A0%3Bs%3A41%3A%221031b8c41dfff97a311a7ac99863bdc5_identity%22%3Bi%3A1%3Bs%3A250%3A%22%5B%221%22%2C%22%5B%5C%22yVQI1wScjIFqbDuwRj_ATB-edFpJgX9vh6uPKwGmU-1my1-DbOPrTMZxsajaaOuw4njRBGkcqgfmp4M12GOkIxY6p2Gj8FHAp2Az%5C%22%2Cnull%2C%5C%22Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_15_6%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F84.0.4147.125+Safari%2F537.36%5C%22%5D%22%2C3600%5D%22%3B%7D; CraftSessionId=501fc4a35b34aff131774e2d24d7a738'
    'HTTP_DNT' => '1'
    'HTTP_HOST' => 'sitenameremoved[mnc].co.uk'
    'HTTP_ORIGIN' => 'https://sitenameremoved[mnc].co.uk'
    'HTTP_REFERER' => 'https://sitenameremoved[mnc].co.uk/admin/sprout-forms/forms/edit/864'
    'HTTP_SEC_FETCH_DEST' => 'empty'
    'HTTP_SEC_FETCH_MODE' => 'cors'
    'HTTP_SEC_FETCH_SITE' => 'same-origin'
    'HTTP_SURROGATE_CAPABILITY' => 'lin-10-170-0-4.gridhost.co.uk=\"Surrogate/1.0 ESI/1.0\"'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36'
    'HTTP_X_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'HTTP_X_FORWARDED_FOR' => '212.90.95.36'
    'HTTP_X_FORWARDED_PROTO' => 'https'
    'HTTP_X_HTTPS' => 'On'
    'HTTP_X_PORT' => '443'
    'HTTP_X_REGISTERED_ASSET_BUNDLES' => ',craft\\web\\assets\\fields\\FieldsAsset,craft\\web\\assets\\cp\\CpAsset,craft\\web\\assets\\axios\\AxiosAsset,craft\\web\\assets\\d3\\D3Asset,craft\\web\\assets\\elementresizedetector\\ElementResizeDetectorAsset,craft\\web\\assets\\garnish\\GarnishAsset,yii\\web\\JqueryAsset,craft\\web\\assets\\jquerytouchevents\\JqueryTouchEventsAsset,craft\\web\\assets\\velocity\\VelocityAsset,craft\\web\\assets\\jqueryui\\JqueryUiAsset,craft\\web\\assets\\jquerypayment\\JqueryPaymentAsset,craft\\web\\assets\\datepickeri18n\\DatepickerI18nAsset,craft\\web\\assets\\picturefill\\PicturefillAsset,craft\\web\\assets\\selectize\\SelectizeAsset,craft\\web\\assets\\fileupload\\FileUploadAsset,craft\\web\\assets\\xregexp\\XregexpAsset,craft\\web\\assets\\fabric\\FabricAsset,barrelstrength\\sproutforms\\web\\assets\\cp\\CpAsset,barrelstrength\\sproutbase\\web\\assets\\cp\\CpAsset,barrelstrength\\sproutforms\\web\\assets\\fontawesome\\FontAwesomeAsset,barrelstrength\\sproutbasefields\\web\\assets\\selectother\\SelectOtherFieldAsset'
    'HTTP_X_REGISTERED_JS_FILES' => ',https://sitenameremoved[mnc].co.uk/cpresources/acf70cc6/axios.min.js?v=1597311958,https://sitenameremoved[mnc].co.uk/cpresources/62120dc0/d3.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/35625269/element-resize-detector.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/d3e919a3/jquery.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/58e719e6/jquery.mobile-events.min.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/bf111a9b/velocity.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/7b4023b2/garnish.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/a7e226b8/jquery-ui.min.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/f56c12f5/jquery.payment.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/c29e7ec2/datepicker-en-GB.js?v=1597313449,https://sitenameremoved[mnc].co.uk/cpresources/746e76e7/picturefill.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/390b6a22/selectize.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/8eb0c4e5/jquery.fileupload.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/7c26b86f/xregexp-all.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/771dc6cd/fabric.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/24f3e7e2/js/Craft.min.js?v=1597311959,https://sitenameremoved[mnc].co.uk/cpresources/fccda024/fields.min.js?v=1597313549,https://sitenameremoved[mnc].co.uk/cpresources/1e673a7f/js/selectotherfield.js?v=1597313549,https://sitenameremoved[mnc].co.uk/cpresources/faf55308/js/sproutforms-cp.js?v=1597313506'
    'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest'
    'PATH' => '/bin'
    'QUERY_STRING' => 'p=admin/actions/sprout-forms/fields/save-field'
    'REDIRECT_STATUS' => '200'
    'REMOTE_ADDR' => '212.90.95.36'
    'REMOTE_PORT' => '35186'
    'REQUEST_METHOD' => 'POST'
    'REQUEST_URI' => '/index.php?p=admin/actions/sprout-forms/fields/save-field'
    'SCRIPT_FILENAME' => '/var/sites/m/sitenameremoved[mnc].co.uk/public_html/index.php'
    'SCRIPT_NAME' => '/index.php'
    'SERVER_ADDR' => '10.170.0.4'
    'SERVER_ADMIN' => 'webmaster@gridhost.co.uk'
    'SERVER_NAME' => 'sitenameremoved[mnc].co.uk'
    'SERVER_PORT' => '443'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'SERVER_SIGNATURE' => ''
    'SERVER_SOFTWARE' => 'Apache'
    'UNIQUE_ID' => 'XzUTAwqqAAQAAGz4fwUAAABj'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1597313795.73
    'REQUEST_TIME' => 1597313795
    'argv' => [
        0 => 'p=admin/actions/sprout-forms/fields/save-field'
    ]
    'argc' => 1
    'ENVIRONMENT' => 'production'
]
```

### Additional info

- Craft version: 3.4.30
- PHP version: 7.3

**Comment by BenParizek** [comment]
Hey @darylknight. I realize you may have found your way past this issue already.

If you're still experiencing this, I'm going to need more details about how you have the field setup. From your error log, it appears the error is being caused by a compiled template which makes me think that a pre-upgrade version of the template code might be throwing the error instead of the latest code and that clearing the template cache may resolve (have resolved) things.

```
Array to string conversion in /var/sites/m/sitenameremoved[mnc].co.uk/storage/runtime/compiled_templates/50/504d6126cb07e47aa6578c246032caba066da7c67c862042f314988bc5525a16.php:123
```

**Comment by darylknight** [comment]
Thanks for checking Ben. Sprout Forms is no longer installed on this site, so I think we can close this specific issue.

**Comment by kerrig** [comment]
I'm currently running into this exact issue.
Sprout Forms Lite v3.13.2.3

I attempted to clear my compiled template cache and it fixed it on first save but attempting to edit the email dropdown field again will not save and throws the error (even after trying to clear the compiled template cache again). I just freshly installed this plugin on this site so it wasn't updated from a previous version.

The error & stack trace from web.log: [sproutform-emaildropdown-error.log](https://github.com/barrelstrength/craft-sprout-forms/files/6005227/sproutform-emaildropdown-error.log)
