### ISSUE TITLE
Form hits error when sending notification

### ISSUE THREAD

**Issue by simonda86** [barrelstrength/craft-sprout-forms#538]
I've recently updated a site from Craft 2 to Craft 3, I'm now getting an error when submitting one of the forms, full stack trace below.

```
2020-10-20 11:28:04 [-][-][uni2o6v5eaeig7lkjkc6koemod][error][barrelstrength\sproutbaseemail\services\NotificationEmailEvents::handleDynamicEvent] When a form entry is saved (Sprout Forms) event does not validate: {"event":["The Form associated with the saved Form Entry Element does not match any selected Forms."]}
2020-10-20 11:28:04 [-][-][uni2o6v5eaeig7lkjkc6koemod][error][TypeError] TypeError: Argument 1 passed to craft\web\View::renderTemplate() must be of the type string, null given, called in /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/barrelstrength/sprout-base-email/src/base/EmailTemplates.php on line 145 and defined in /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/craftcms/cms/src/web/View.php:371
Stack trace:
#0 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/barrelstrength/sprout-base-email/src/base/EmailTemplates.php(145): craft\web\View->renderTemplate(NULL, Array)
#1 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/barrelstrength/sprout-base-email/src/base/EmailTemplates.php(100): barrelstrength\sproutbaseemail\base\EmailTemplates->processEmailTemplates()
#2 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/barrelstrength/sprout-base-email/src/base/Mailer.php(148): barrelstrength\sproutbaseemail\base\EmailTemplates->getTextBody()
#3 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/barrelstrength/sprout-base-email/src/mailers/DefaultMailer.php(105): barrelstrength\sproutbaseemail\base\Mailer->getMessage(Object(barrelstrength\sproutbaseemail\elements\NotificationEmail))
#4 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/barrelstrength/sprout-base-email/src/services/NotificationEmails.php(115): barrelstrength\sproutbaseemail\mailers\DefaultMailer->sendNotificationEmail(Object(barrelstrength\sproutbaseemail\elements\NotificationEmail))
#5 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/barrelstrength/sprout-base-email/src/services/NotificationEmailEvents.php(227): barrelstrength\sproutbaseemail\services\NotificationEmails->sendNotificationViaMailer(Object(barrelstrength\sproutbaseemail\elements\NotificationEmail))
#6 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/barrelstrength/sprout-base-email/src/services/NotificationEmailEvents.php(153): barrelstrength\sproutbaseemail\services\NotificationEmailEvents->handleDynamicEvent('barrelstrength\\...', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent), Object(barrelstrength\sproutforms\integrations\sproutemail\events\notificationevents\SaveEntryEvent))
#7 [internal function]: barrelstrength\sproutbaseemail\services\NotificationEmailEvents::barrelstrength\sproutbaseemail\services\{closure}('barrelstrength\\...', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent), Object(barrelstrength\sproutforms\integrations\sproutemail\events\notificationevents\SaveEntryEvent))
#8 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/barrelstrength/sprout-base-email/src/services/NotificationEmailEvents.php(122): call_user_func(Object(Closure), 'barrelstrength\\...', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent), Object(barrelstrength\sproutforms\integrations\sproutemail\events\notificationevents\SaveEntryEvent))
#9 [internal function]: barrelstrength\sproutbaseemail\services\NotificationEmailEvents::barrelstrength\sproutbaseemail\services\{closure}(Object(barrelstrength\sproutforms\events\OnSaveEntryEvent))
#10 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(barrelstrength\sproutforms\events\OnSaveEntryEvent))
#11 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('barrelstrength\\...', 'afterSave', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent))
#12 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/barrelstrength/sprout-forms/src/services/Entries.php(294): yii\base\Component->trigger('afterSave', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent))
#13 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/barrelstrength/sprout-forms/src/services/Entries.php(177): barrelstrength\sproutforms\services\Entries->callOnSaveEntryEvent(Object(barrelstrength\sproutforms\elements\Entry), true)
#14 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/barrelstrength/sprout-forms/src/controllers/EntriesController.php(251): barrelstrength\sproutforms\services\Entries->saveEntry(Object(barrelstrength\sproutforms\elements\Entry))
#15 [internal function]: barrelstrength\sproutforms\controllers\EntriesController->actionSaveEntry()
#16 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#18 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('save-entry', Array)
#19 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#20 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('sprout-forms/en...', Array)
#21 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('sprout-forms/en...', Array)
#22 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#23 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#24 /var/www/vhosts/inlandhomes.co.uk/dev.inlandhomes.co.uk/web/index.php(21): yii\base\Application->run()
#25 {main}
```

When I'm looking at the `sproutemail_notificationemails` table there are blank values, I'm wondering if this is causing the issue?

<img width="1197" alt="Screenshot 2020-10-20 at 14 56 56" src="https://user-images.githubusercontent.com/495114/96596529-ba289f80-12e4-11eb-9f3a-9901db233b6f.png">

### Additional info

- Craft version: Craft Pro 3.5.13
- PHP version: 7.3.23
- Database driver & version:  MySQL 5.5.55
- Plugins & versions: dev-craft-3.5

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_341u5)

**Comment by BenParizek** [comment]
Thanks @simonda86. I'm working on Craft 3.5 support this week. I'll update this thread once I get that out.

**Comment by terence1990** [comment]
Hey @simonda86 

Just been looking through old issues and this one: https://github.com/barrelstrength/craft-sprout-forms/issues/394 has a reference the same error message:

"The Form associated with the saved Form Entry Element does not match any selected Forms."

He said he fixed it:

"I "fixed" the disappearing fields issue before seeing your recommendations in that thread—and did it manually by updating the DB to update the fieldLayoutId column of the craft_sproutforms_forms table to point to the correct / corresponding id in the craft_fieldlayouts table.

After doing that everything seems to be working properly again (forms submit successfully on the front end, entries are saved and displayed in the CP, notifications sent)."

Not sure if this helps at all!

**Comment by simonda86** [comment]
Thanks @terence1990 

I've been looking at this a bit further and I noticed that these 4 rows with the null values don't appear on the old Craft 2 site, so I've deleted these and it's working now!

**Comment by BenParizek** [comment]
This was due to a migration bug where the Craft 2 Form Notification Email did not get saved with an Email Template ID. I'll get a fix in the next release and if anybody run into this before then, resaving any Form Notification Emails should get the correct values in the db and correct this issue.

**Comment by BenParizek** [comment]
This should be addressed in the latest release of Sprout Forms. 

I'm catching up on several support tickets right now and working on a large update to improve the migration process that has been causing a lot of issues in our plugins. There will likely be several smaller updates coming out over the next couple of weeks so, if possible, I'd recommend holding off on updating until we get Sprout Forms v4.0 out the door which should get things into a lot better shape and address number of smaller issues all at once.
